### ISSUE TITLE
error when launching exe

### ISSUE THREAD

**Issue by Progamer7867lol** [artumino/VRScreenCap#20]
INFO - Trying to elevate process priority
ERROR - thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ERROR_RUNTIME_UNAVAILABLE': src\engine\vr.rs:32
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: BaseThreadInitThunk
  18: RtlUserThreadStart

INFO - Trying to elevate process priority
ERROR - thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ERROR_RUNTIME_UNAVAILABLE': src\engine\vr.rs:32
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: BaseThreadInitThunk
  18: RtlUserThreadStart

INFO - Trying to elevate process priority
ERROR - thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ERROR_RUNTIME_UNAVAILABLE': src\engine\vr.rs:32
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: BaseThreadInitThunk
  18: RtlUserThreadStart

INFO - Trying to elevate process priority
ERROR - thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ERROR_RUNTIME_UNAVAILABLE': src\engine\vr.rs:32
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: BaseThreadInitThunk
  18: RtlUserThreadStart

**Comment by Progamer7867lol** [comment]
wht does it mean
